# Generated by Django 4.0.4 on 2022-05-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignments',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
