# Generated by Django 4.0.4 on 2022-05-18 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreAPI', '0002_alter_studentassignments_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignments',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
