# Generated by Django 4.0.4 on 2022-05-18 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoreAPI', '0003_studentassignments_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignments',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
