# Generated by Django 4.0.4 on 2022-05-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreAPI', '0006_alter_studentassignments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
